export { default as SectionHero } from './section-hero'
export { default as SectionHowWorks } from './section-how-works'
export { default as SectionAbout } from './section-about'
export { default as SectionSponsors } from './section-sponsors'
export { default as SectionTeam } from './section-team'
